.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2019 Henrik Hedelund <debian@henhed.se>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CIK 1 "July 14 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cik \- Simple key-value store
.SH SYNOPSIS
.B cik
.RI [ "config file" ]
.SH DESCRIPTION
This manual page documents briefly the
.B cik
command.
.PP
.B cik
is a key-value database in a similar vein to memcache.
.B cik
additionally provides native support for key-tag-relations for granular control
over removal of a data subsets.  The complete dataset is stored entirely in
memory and flushed to disk on program exit.
.SH OPTIONS
.B cik
takes no options.
